---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  gather_facts: no

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  gather_facts: no

  roles:
    - db
