- hosts: localhost
  gather_facts: no

  vars:
    resource_group: "{{ resource_group_name | default('RG_Ansible') }}"
    pfx: "{{ 100000 | random() }}"
    current_timestamp: "{{ '%Y-%m-%d' | strftime }}"
    network_name: "rh_network"
    subnet_name: "demo_subnet"
    location: eastus
    azure_tags:
      creator: 'ansible'
      organization: 'produccion'
      family: 'CloudDemo' 
    vm_list: 
    - vm_name: "web3"
    - vm_name: "web2"

  roles:
  - azure
 
