---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql from Repo
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    state: present

- name: Install Mysql extra packages
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages: 
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: Start Mysql Service
  service: 
    name: mysqld 
    state: started 
    enabled: yes

- name: insert iptables rule for MySQL
  iptables:
    chain: INPUT
    destination_port: "{{ mysql_port }}"
    jump: ACCEPT
    protocol: tcp
  notify: restart iptables

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
